"""Check recall floor — fails build if any entity type recall < 0.95.

Reads benchmarks/recall-results.json (generated by benchmarks/recall.py)
and exits with code 1 if any detector/entity-type pair has recall below 0.95.

KNOWN EXCEPTIONS: Entity types listed in known_exceptions won't fail the
build but will produce a WARNING. Add entries here when a type is a documented
known limitation that will be addressed in a planned improvement.
Format: ("<detector>", "<entity_type>") — e.g. ("regex", "ADDRESS")

Expected JSON structure:
  {
    "detectors": {
      "<detector_name>": {
        "per_type": {
          "<entity_type>": {"recall": <float>, ...},
          ...
        }
      }
    }
  }
"""

import json
import sys

THRESHOLD = 0.95
RESULTS_PATH = "benchmarks/recall-results.json"

# Known exceptions — types below 0.95 that are documented limitations.
# These produce a WARNING instead of failing the build.
known_exceptions: set[tuple[str, str]] = {
    # Add entries here as needed, e.g.
    # ("regex", "ADDRESS"),
}
def main() -> None:
    try:
        with open(RESULTS_PATH) as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"FAIL: {RESULTS_PATH} not found — run benchmarks/recall.py first")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"FAIL: {RESULTS_PATH} is not valid JSON — {e}")
        sys.exit(1)

    detectors = data.get("detectors", {})
    if not detectors:
        print("FAIL: No 'detectors' key found in results file")
        sys.exit(1)

    failures: list[str] = []
    warnings: list[str] = []

    for detector_name, det_data in detectors.items():
        per_type = det_data.get("per_type", {})
        for entity_type, metrics in per_type.items():
            recall = metrics.get("recall", 1.0)
            if recall < THRESHOLD:
                line = (
                    f"  {detector_name}/{entity_type}: recall={recall:.4f} "
                    f"(TP={metrics.get('true_positives', '?')}, "
                    f"FN={metrics.get('false_negatives', '?')})"
                )
                key = (detector_name, entity_type)
                if key in known_exceptions:
                    warnings.append(line)
                else:
                    failures.append(line)

    if warnings:
        print(f"WARNING: {len(warnings)} known exception(s) below recall floor {THRESHOLD}")
        for line in warnings:
            print(line)

    if failures:
        print(f"FAIL: {len(failures)} entity type(s) below recall floor {THRESHOLD}")
        for line in failures:
            print(line)
        sys.exit(1)

    # Print healthy summary when everything passes
    print(f"OK: All entity types at or above recall floor {THRESHOLD}")
    for detector_name, det_data in detectors.items():
        per_type = det_data.get("per_type", {})
        at_floor = sum(1 for m in per_type.values() if m.get("recall", 0) >= THRESHOLD)
        below = sum(1 for m in per_type.values() if m.get("recall", 0) < THRESHOLD)
        print(f"  {detector_name}: {at_floor} at floor, {below} below")


if __name__ == "__main__":
    main()