"""SemanticStrategy — replaces PII with realistic fake data via generate_alias()."""

from __future__ import annotations

from logging import getLogger
from typing import Any

from piifilter.interfaces.strategy import ReplacementStrategy
from piifilter.shared.models import DetectedEntity, EntityType, Replacement, ReplacementMode
from piifilter.shared.utils import generate_alias

logger = getLogger(__name__)


class SemanticStrategy(ReplacementStrategy):
    """Replacement strategy that substitutes PII with semantically similar
    fake data using deterministic aliases.

    Each detected entity is replaced by a contextually appropriate
    pseudonym generated by ``piifilter.shared.utils.generate_alias()``.
    The same original value always maps to the same alias, making the
    replacement reversible for audit and debugging purposes.

    Entities are processed in reverse position order (end-of-string first)
    so that earlier replacements do not shift the character offsets of
    later replacements.
    """

    def __init__(self, **kwargs: Any) -> None:
        self._name = kwargs.pop("name", "semantic")

    # ── ReplacementStrategy interface ──────────────────────────────────

    @property
    def name(self) -> str:
        return self._name

    async def apply(self, text: str, detections: list[dict]) -> str:
        """Apply semantic replacement to detected PII in *text*.

        Args:
            text: The original prompt text.
            detections: A list of detection dicts, each expected to have
                at least ``start``, ``end``, and ``type`` (or ``entity_type``) keys.

        Returns:
            The text with all detected spans replaced by semantic aliases.
        """
        reversed_detections = sorted(
            detections,
            key=lambda d: d.get("end", d.get("start", 0)),
            reverse=True,
        )
        result = text
        for d in reversed_detections:
            start = d["start"]
            end = d.get("end", start)
            original = result[start:end]
            alias = generate_alias(original)
            result = result[:start] + alias + result[end:]
        return result

    async def replace(
        self,
        session: Any,
        entities: list[DetectedEntity],
    ) -> tuple[str, list[Replacement]]:
        """Replace detected entities in the session prompt with semantic aliases.

        Args:
            session: The pipeline ``Session`` object (provides ``session.prompt``,
                and optionally ``session.config.replacement.seed`` to control
                the deterministic seed passed to ``generate_alias()``).
            entities: List of ``DetectedEntity`` instances to replace.

        Returns:
            A tuple of ``(filtered_text, replacements)`` where *replacements*
            is a list of ``Replacement`` dataclass instances recording every
            substitution.
        """
        prompt = session.prompt
        seed = session.config.replacement.seed if hasattr(session, "config") else "deterministic"
        replacements: list[Replacement] = []

        # Process in reverse position order so offsets remain valid
        sorted_entities = sorted(entities, key=lambda e: e.end, reverse=True)

        for entity in sorted_entities:
            alias = generate_alias(entity.value, seed=seed)
            prompt = prompt[: entity.start] + alias + prompt[entity.end :]

            replacements.append(
                Replacement(
                    original=entity.value,
                    replacement=alias,
                    entity_type=entity.type,
                    start=entity.start,
                    end=entity.start + len(alias),
                    mode=ReplacementMode.SEMANTIC,
                    reversible=True,
                    metadata={"entity_type": entity.type.value},
                )
            )

        logger.debug(
            "SemanticStrategy applied %d replacement(s)", len(replacements)
        )
        return prompt, replacements

    async def initialize(self) -> None:
        logger.info("SemanticStrategy initialized")

    async def shutdown(self) -> None:
        logger.info("SemanticStrategy shut down")